version: '3.9'

services: 
  # Mongodb services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes: 
      - mongo_db:/data/db

  #Node API service
  api: 
    build: .
    ports: 
      - 3010:3010
    volumes:
      - .:/usr/src/whatodo-server
    environment:
      PORT: 3010
      MONGODB_URI: mongodb://mongo_db:27017/whatodo
      NAME: Whatodo
      TOKEN_SECRET: XXXXXXX
      REFRESH_TOKEN_SECRET: XXXXXXX
      HASH_PWD_SECRET: P@cKm@n@G3RCørP;
      MODE: DEVELOPMENT
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}