export const ActivityStringsConstant = {

    DISCOVERING: [] = ["tourist_attraction", /*"bowling_alley", "stadium", "gym"*/],
    RESTAURANT: [] = ["restaurant"],
    BAR: [] = ["bar"],
    RANDOM: [] = ["restaurant", "bar", "bakery", "cafe",
        "tourist_attraction",
        "shoe_store", "jewelry_store", "home_goods_store",
        "furniture_store", "clothing_store"
    /*"amusement_park",
        "aquarium",
        "art_gallery",
        "book_store",
        "cemetery",
        "church",
        "city_hall",
        "courthouse",
        "embassy",
        "florist",
        "hindu_temple",
        "library",
        "mosque",
        "movie_theater",
        "museum",
        "park",
        "spa",
        "subway_station",
        "synagogue",
        "tourist_attraction",
        "university",
        "zoo",
        "casino"*/,
    ],

    SNACKING: [] = ["bakery", "cafe"],
    SHOPPING: [] = ["shoe_store", "jewelry_store", "home_goods_store", "furniture_store", "clothing_store"]
}