export const ActivityStringsConstant = {

    SPORT: [] = ["bowling_alley", "stadium", "park", "gym"],
    RESTAURANT: [] = ["restaurant"],
    BAR: [] = ["bar"],
    CULTUREL: [] = ["amusement_park",
        "aquarium",
        "art_gallery",
        "book_store",
        "cemetery",
        "church",
        "city_hall",
        "courthouse",
        "embassy",
        "florist",
        "hindu_temple",
        "library",
        "mosque",
        "movie_theater",
        "museum",
        "park",
        "spa",
        "subway_station",
        "synagogue",
        "tourist_attraction",
        "university",
        "zoo",
        "casino",
    ],

    SNACKING: [] = ["bakery", "cafe"],
    SHOPPING: [] = ["shopping_mall", "shoe_store", "jewelry_store", "home_goods_store", "furniture_store", "department_store", "clothing_store"]
}